### PR TITLE
Make test status message unclickable

### LINKED ISSUE #261: Failed behaves like a clickable button that does nothing
animates like a button but it isn't

Screen Shot 2020-06-25 at 10 28 53

### PR DESCRIPTION
**Pull request by ghost**
This fixes #261.

The test results status uses a button to display if the test failed.  This fix changes this by using a card to display this information.  The use of an HTML table helps with the formatting to ensure the look has the same aesthetics.

The following files were modified:
+ /src/components/cards/controltable/ControlRowCol.vue

### CODE REVIEW

File: src/components/cards/controltable/ControlRowCol.vue [hunk 1]
```diff
@@ -2,9 +2,17 @@
...
+          <tr>
+            <td style="text-align:center">
+              <v-card :color="status_color">
+                <v-card-text class="pa-2 font-weight-bold">
+                  <h3>{{ result.status.toUpperCase() }}</h3>
+                </v-card-text>
+              </v-card>
+            </td>
+          </tr>
+        </table>
```
Comment (rbclark) [inline src/components/cards/controltable/ControlRowCol.vue]: I think adding `class='disabled-btn'` and adding a `disabled-btn` class in the css below as described in https://stackoverflow.com/a/54309684/1670307 is probably a simpler solution, add an inline table for this seems a little overkill.

**Review by rbclark — CHANGES_REQUESTED** [review]

File: src/components/cards/controltable/ControlRowCol.vue (hunk 1 above)
Comment (ghost) [reply src/components/cards/controltable/ControlRowCol.vue]: Created a new classname called 'unclickablebutton' as a class attribute on the button element.  Created a scoped CSS entry on the page to disable the button and remove transparency.

The following files were modified:
+ /src/components/cards/controltable/ControlRowCol.vue

Comment (ghost) [reply src/components/cards/controltable/ControlRowCol.vue]: Removed the transparency attribute from the CSS section.

**Review by rbclark — APPROVED** [review]
